#!/usr/bin/env python

"""Executable to run helloworld"""

import sys
from pathlib import Path

rootdir = Path(__file__).parent.parent
sys.path.append(str(rootdir))

from helloworld.main import main

main()